export const countryCodeOptions = [
  { country: 'Nigeria', code: '+234' },
  { country: 'United Kingdom', code: '+44' },
  { country: 'United States', code: '+1' },
  { country: 'Canada', code: '+1' },
  { country: 'Ghana', code: '+233' },
  { country: 'Kenya', code: '+254' },
  { country: 'South Africa', code: '+27' },
  { country: 'United Arab Emirates', code: '+971' },
  { country: 'India', code: '+91' },
  { country: 'China', code: '+86' },
  { country: 'Turkey', code: '+90' },
  { country: 'Germany', code: '+49' },
  { country: 'France', code: '+33' },
  { country: 'Italy', code: '+39' },
  { country: 'Spain', code: '+34' },
];
